version: 2
jobs:
    test-node10:
        working_directory: ~/utils
        docker:
            - image: "circleci/node:10-browsers"
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-
            - run:
                  name: Install
                  command: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Test
                  command: yarn test:coverage
            - run:
                  name: Codecov
                  command: ./node_modules/.bin/codecov
            - run:
                  name: Benchmark
                  command: yarn bench
    test-node11:
        working_directory: ~/utils
        docker:
            - image: "circleci/node:11-browsers"
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-
            - run:
                  name: Install
                  command: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Test
                  command: yarn test:coverage
            - run:
                  name: Codecov
                  command: ./node_modules/.bin/codecov
            - run:
                  name: Benchmark
                  command: yarn bench
    test-node12:
        working_directory: ~/utils
        docker:
            - image: "circleci/node:12-browsers"
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-
            - run:
                  name: Install
                  command: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Test
                  command: yarn test:coverage
            - run:
                  name: Codecov
                  command: ./node_modules/.bin/codecov
            - run:
                  name: Benchmark
                  command: yarn bench
workflows:
    version: 2
    build_and_test:
        jobs:
            - test-node10
            - test-node11
            - test-node12
